# -*- coding: utf-8 -*-
"""Conversor Heic_PNG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V50iCCUpykJDesDD5JfMPSXMHgWj0qbg
"""

pip install pyheif

from glob import glob
from PIL import Image
import pyheif

input_dir = '/content/drive/MyDrive/convert_HEIF_TO_PNG/*.HEIC'
output_dir = "/content/drive/MyDrive/converted_HEIF_TO_PNG/"
count = 1

for file_path in glob(input_dir):
    heif_file = pyheif.read(file_path)

    image = Image.frombytes(
        heif_file.mode,
        heif_file.size,
        heif_file.data,
        "raw",
        heif_file.mode,
        heif_file.stride,
      )

    image.save(output_dir + str(count) + '.png', 'PNG')

    print(f'Image {count} converted!')
    count += 1